name: Test and Release
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3   
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Test
        run: |
          go test ./...
      - name: Build
        run: go build -v -trimpath -ldflags "-s -w -buildid=" .
